### ISSUE TITLE
Very old Adyen API version

### ISSUE THREAD

**Issue by mpchlets** [killbill/killbill-adyen-plugin#101]
It seems that this is using Adyen v12 of the API, but they are on like v40 - is there any chance to update this to the latest API? Or have any suggestions working with it in Adyen Production as is?

Thanks

**Comment by pierre** [comment]
We have no plan to upgrade the API version at this time.

Reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) if you have specific needs from a more recent version and we'll explore your options. 

See also [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
