### ISSUE TITLE
Make timeouts configurable

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-adyen-plugin#17]
org.killbill.billing.plugin.adyen.client.AdyenPaymentPortRegistry#createService needs to set a HTTPClientPolicy with configurable timeouts.

At the moment Apache CXF default timeouts are used:
* Connection: 30s
* Receive: 60s

**Comment by BLangendorf** [comment]
@pierre looks like this already was done in commit 6a67fbfd0f44fbae14b44c312ff53b05fe4da357 by @arnelandwehr (around the same time this issue was opened)

**Comment by arnelandwehr** [comment]
some minor things are missing:
- documentation of the properties
- sane defaults

**Comment by BLangendorf** [comment]
@pierre @arnelandwehr 
What would be _sane defaults_ for this?

**Comment by pierre** [comment]
How about keeping 30s and 60s?
