### ISSUE TITLE
Recurring contract should be configurable

### ISSUE THREAD

**Issue by arnelandwehr** [killbill/killbill-adyen-plugin#19]
Adyen offers 3 different options to create recurring contracts on auth calls:

1. RECURRING
2. ONE-CLICK
3. RECURRING, ONE-CLICK

(see adyens recurring manual for more information: [manual](https://docs.adyen.com/display/TD/Recurring+Manual))

Currently the plugin always uses option 3: https://github.com/killbill/killbill-adyen-plugin/blob/26e4ad4e6c491db5baad7036de814a648d185095/src/main/java/org/killbill/billing/plugin/adyen/client/payment/builder/PaymentRequestBuilder.java#L150

Which contract to create should be configurable (there is also already a plugin property for it)

**Comment by pierre** [comment]
We should also [document the behavior](https://github.com/killbill/killbill-adyen-plugin/pull/14#discussion_r41135172) in the README and/or code.
