### ISSUE TITLE
PSP Result is not inserted to DB correct

### ISSUE THREAD

**Issue by BLangendorf** [killbill/killbill-adyen-plugin#23]
Problem
-----------
The PSP Result is an `Optional`:
```
private final Optional<PaymentServiceProviderResult> result;
```
Currently it gets inserted using `toString()`:
```
result.getResult() == null ? null : result.getResult().toString(),
```
That results in something like this as Text in the DB:
```
Optional.of(Authorised)
```
Solution
-----------
Replace `== null` check with a `.isPresent()` and `toString()` with `get().toString()`

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-adyen-plugin/pull/24.
