### ISSUE TITLE
Add support for custom additionalData parameters

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-adyen-plugin#83]
This could be useful for result code testing for instance: https://docs.adyen.com/developers/risk-management/result-code-testing.

**Comment by breynolds-squaretrade** [comment]
Would you be getting the result code information from the payment method plugin properties?

**Comment by pierre** [comment]
The `refusalReason` would actually be in the `GatewayError`error field. See https://github.com/killbill/killbill-adyen-plugin/pull/84/files#diff-b2bac21392b3eb73e104dc5c73aa52c5R666 for an example.
